POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "hellas"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json


{
  "title": "Test - Blog 2",
  "author": "David",
  "url": "http://testblog222.com",
  "likes": 9

}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwiaWQiOiI2Nzc5MTJmNzlmNTg5NWIxMjM3ZTY3MzEiLCJpYXQiOjE3MzYwMTgwMDYsImV4cCI6MTczNjAyMTYwNn0.LFiDmbdoMBux5nuvjiQfcsgvKZZMu1vUulGKS6wBThM

{
  "title": "Test 2",
  "author": "Arto Hellas",
  "url": "http://testblog2.com",
  "likes": 5

}
###
GET http://localhost:3003/api/blogs/6778667fdcbac6602e4bdd0c

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "test"
}